// Mocks generated by Mockito 5.4.2 from annotations
// in doctus_test/test/features/cats/app/cubits/cats_cubits_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:doctus_test/features/cats/domain/models/cat.dart' as _i2;
import 'package:doctus_test/features/cats/domain/repositories/cats_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCat_0 extends _i1.SmartFake implements _i2.Cat {
  _FakeCat_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CatsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatsRepository extends _i1.Mock implements _i3.CatsRepository {
  MockCatsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Cat> getCat() => (super.noSuchMethod(
        Invocation.method(
          #getCat,
          [],
        ),
        returnValue: _i4.Future<_i2.Cat>.value(_FakeCat_0(
          this,
          Invocation.method(
            #getCat,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Cat>);
}
